/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/


public class Problem2{
	public static void main(String[] args){
		int acum = 0;
		int num1 = 0;
		int num2 = 0;

		for(int i=1; i<=4000000; i = num1+num2){
			if(i%2 == 0){
				acum += i;
			}

			num1 = num2;
			num2 = i;
		}

		System.out.println(acum);
	}
}